### ISSUE TITLE
Mudar nome do repositório

### ISSUE THREAD

**Issue by gjuniioor** [bahiacoders/bahiacoders.github.io#1]
Opa!

Gostaria de recomendar a mudança do nome do repositório de bahiacoders.org para bahiacoders.github.io.

Assim, o site fica online sob a url bahiacoders.github.io e caso queira utilizar um domínio personalizado, só colocar o arquivo CNAME. Ficando como está atualmente, para a pessoa ver o blog tem de baixar e rodar o jekyll localmente.

**Comment by mvfsilva** [comment]
Fala @gjuniioor, primeiramente obrigado por querer contribuir, irei fazer isso agora!

**Comment by gjuniioor** [comment]
Estranho que até agora (duas horas depois) ainda está dando 404 O.o

Bem, deve demorar mais para replicar.

**Comment by jjaderg** [comment]
Opa, o repositório tem esse domínio porque pelo fato de após o desenvolvimento, ele subirá pelo `github-pages` sem o github.io. Assim fica melhor para o intuito do projeto e também para o fácil acesso de outros que não sejam tão familiarizados com o Github.

Em contra partida, podemos muda-lo para o domínio `.com`, por ser mais barato e também de fácil acesso como já disse anteriormente!

**Comment by mvfsilva** [comment]
@jjaderg basta criar um arquivo CNAME e apontar para url desejada e done.

**Comment by gjuniioor** [comment]
@jjaderg , é como o @mvfsilva falou, só criar um arquivo `CNAME` e uma entrada dessa no registro do domínio. O bom de ter o repositório com esse nome é que ele já está online em: https://bahiacoders.github.io.

E já resolveu, então, agora podemos fechar :P
