### ISSUE TITLE
União de projetos

### ISSUE THREAD

**Issue by mvfsilva** [bahiacoders/bahiacoders.github.io#11]
Galera boa noite, hoje fui adicionado a uma nova organização chamada [devBahia](https://github.com/devinbahia) e sugerir a união dos mesmos, já que possuímos o mesmo proposito que é se tornar um container para as comunidades da Bahia.

**Comment by gjuniioor** [comment]
Cara, unir é uma boa, já que é o objetivo do Bahia Coders. A questão é ver se a ideia de um e outro projeto tem mais interseção.

**Comment by paulodealmeida** [comment]
@mvfsilva e @gjuniioor o que nós queriamos era justamente ter um ponto focal das comunidades para qualquer proposito, o inicial seriam os eventos.

**Comment by mvfsilva** [comment]
Ótimo @paulodealmeida, vamos mandar bala, começando com esse projeto de eventos, pq estão rolando vários na cidade e etc...

**Comment by paulodealmeida** [comment]
Vamos sim, a parte de eventos será uma seção do site principal ou será algo a parte?

**Comment by paulodealmeida** [comment]
Vamos mudar tb o layout do site, dá uma olhada no #2 que tem uma lista de sugestões.

**Comment by gjuniioor** [comment]
Acho bacana ser algo a parte ... Um repositório bem criativo chamado "agenda" :D

**Comment by paulodealmeida** [comment]
@gjuniioor um repo separado ou uma parte desse mesmo? No mesmo formato json do php-business-ba?

**Comment by gjuniioor** [comment]
Separado acho mais vantagem, pq ai pode mexer em tudo de forma livre. Fica ai para decidir se vai em formato json ou bota um jekyll da vida.

**Comment by mvfsilva** [comment]
Concordo @gjuniioor e @paulodealmeida
