### ISSUE TITLE
Tema e intuito do site

### ISSUE THREAD

**Issue by gjuniioor** [bahiacoders/bahiacoders.github.io#2]
Achei bacana quando falaram desse grupo no GDG, então, bora tocar pra frente!

Recentemente fizemos o [blog do phpba](http://phpba.com.br) e foi uma coisa bem dinâmica e rápida. Em [dois dias](https://groups.google.com/forum/#!topic/phpba/g21is31xK6M) já estava tudo no ar e funcionando. Vamos ver se conseguimos fazer aqui ser assim também :)

Para isso, ao meu ver, "precisa" definir basicamente duas coisas:

* Intuito
* Layout

1. Intuito

Minha ideia é que já que a comunidade de desenvolvimento da Bahia está començando a se unir, independente de tecnologia, esse pode ser um blog geral, para tratar de eventos futuros, como foram esses eventos, disponibilizar apresentações e materiais e coisas do tipo. Acredito que assim, vai fomentar ainda mais a união. *-*

2. Layout

Assim como falei na lista do PHPBA, não sou da parte de front. Então, caso queiram, seleciona um tema pronto ai e a gente mete bala! Arruma e edita o que tiver de fazer e pronto. Caso a galera de front de plantão queira fazer o layout, massa!! Daí só ir fazendo e arrumando ai que vamos fazendo acontecer.

Então, o que me dizem?

> Para sugerir temas, gosto de linkar esses dois:
>
> * http://jekyllthemes.org/
> * http://jekyllthemes.io/

**Comment by mvfsilva** [comment]
Sobre o tema/layout estamos pensando em qual tema da Bahia iremos utilizar, tem alguma sugestão?

**Comment by jjaderg** [comment]
Boa indagação @gjuniioor, em si nesse projeto temos como inspiração o http://minasdev.org/. Como você vai conferir, é algo um pouco mais "formal", a ideia é realmente centralizar toda comunidade aqui independente de que tecnologia seja. Com relação ao layout, de inicio é criar algo  minimalista mas com a cara de nós baianos! :) .

**Comment by jonataa** [comment]
Layout == designer. Temos? :)

Pq não pegar um layout azul e uma foto da bahia, pelo menos tiramos essa ideia do papel.

As seções do site nesse momento seriam:
* O que é o BahiaCoders (descrição na capa);
* Comunidades parceiras (já fizeram o convite? Posso ajudar nisso daqui);
* Newsletters (fique por dentro dos eventos de desenvolvedores que acontecerão na Bahia);
* Seja nosso parceiro!

**Comment by jjaderg** [comment]
Por aí mesmo @jonataa.

**Comment by jonataa** [comment]
Vamos fazer os convites às comunidades e solicitar a logo para o site. Criei uma [issue](https://github.com/bahiacoders/bahiacoders.github.io/issues/3) para começarmos a trabalhar nisso.

**Comment by jonataa** [comment]
@jjaderg vou criar um issue para cada seção do site, assim conseguimos dividir melhor o trabalho.

**Comment by gjuniioor** [comment]
Quanto a design não é comigo (kkk), mas vou buscar ajudar em todo o restante.

**Comment by mvfsilva** [comment]
Posso tentar falar com a Tati, ela que deu show na nova logo do GDGSSA

**Comment by gjuniioor** [comment]
@mvfsilva , criei uma nova issue para isso da logo. Qualquer atualização, bota lá :P

**Comment by jonataa** [comment]
Seria muito bom se ela fizer, @mvfsilva!

**Comment by mvfsilva** [comment]
Beleza!

**Comment by paulodealmeida** [comment]
Fiz uma apanhado dos temas e eis os que mais me agradaram


1. http://jekyllthemes.org/themes/singlepaged/
2. http://jekyllthemes.org/themes/solid/
3. http://jekyllthemes.org/themes/personal/
4. http://jekyllthemes.org/themes/moon/
5. http://jekyllthemes.org/themes/evento/
6. http://jekyllthemes.org/themes/creative-theme/
7. http://jekyllthemes.org/themes/singlepaged/

Vamos escolher uma deles?

**Comment by mvfsilva** [comment]
@paulodealmeida acho bem válido, vamos por isso no ar logo!

**Comment by mvfsilva** [comment]
Gostei desses dois:
[Solid](http://ojs.xyz/solid-jekyll/)
[Creative](https://volny.github.io/creative-theme-jekyll/)

**Comment by paulodealmeida** [comment]
eu coloquei na ordem dos que eu mais gostei, e o [evento](http://jekyllthemes.org/themes/evento/) para a agenda

**Comment by jjaderg** [comment]
Realmente @paulodealmeida , pra adiantar o lado, vamos usar algum desses listados por voce. Eu acho uma boa o [Solid Jekyll](http://ojs.xyz/solid-jekyll/), para todo contexto do BC e o [Evento](http://evento.davidboyne.co.uk/) para termos um spy event da nossa comunidade!

**Comment by paulodealmeida** [comment]
mandei um PR #12 com o tema solid
como vamos fazer a agenda? um novo repo com o tema evento ou um simples json? ainda estou sem ideias para isso

**Comment by jjaderg** [comment]
Creio que seja melhor um outro repo mesmo @paulodealmeida . Daí fazemos o link pra ele pelo site principal. Final de semana vou da um gás, esses dias tou garrado com o trabalho.

**Comment by gjuniioor** [comment]
Então vambora pra lá! https://github.com/bahiacoders/agenda

**Comment by jjaderg** [comment]
@gjuniioor  ta rápido no gatilho hein, rsrs. Mano aproveita e sobe o http://evento.davidboyne.co.uk/ pra o repositorio. Dái agora é só umas costumizações que vao faltar, mas fds vou investir tempo no projeto e claro quem quiser se jogar, o faça! Vamo que vamo !

**Comment by gjuniioor** [comment]
Na verdade, @jjaderg , temos de decidir a grande questão da vida, universo, estrutura da agenda e tudo mais: https://github.com/bahiacoders/agenda/issues/1 hehe
