### ISSUE TITLE
Criar um texto explicando o que é o Bahia Coders e seu principal objetivo

### ISSUE THREAD

**Issue by jonataa** [bahiacoders/bahiacoders.github.io#4]
Esse texto será utilizado na página e nas redes sociais do grupo. Não precisa ser um texto longo, acho que um parágrafo resolve.

**Comment by gjuniioor** [comment]
O que acham desse rabisco:

"O mundo precisa de menos fronteiras, menos preconceitos, menos barreiras. O mundo da tecnologia não escapa disso. Bahia Coders veio para unir toda a comunidade de desenvolvedores da Bahia independente de paradigma, editor ou linguagem."

**Comment by jonataa** [comment]
Rabisco??? Muito bom, gostei! :+1:

**Comment by mvfsilva** [comment]
Rabisco??? Muito bom, gostei! :+1: [2]

**Comment by gjuniioor** [comment]
:smile: 

Vocês que decidem ai :P

**Comment by jonataa** [comment]
Posso fechar essa issue? Acho que já resolvemos =)

**Comment by gjuniioor** [comment]
Por mim, ok. Se for fazer as coisas por votação, já são dois aqui :P

**Comment by mvfsilva** [comment]
Done!
